language: java

after_script: echo $Foo

script: 
  - cd sdk ; mvn test
  - echo $test1
  - echo $testproj
  
jdk:
  - oraclejdk7
  - oraclejdk8

env:
 global:
   - Foo=bar
   #- test1=aa
 matrix:
   - secure: m7dPwmLIQK8gcik8myto3FRUaF6SLoBJ+mi3xaYAi9bRfME9lVvOLSKjIez+mA7erGtqWAsqaGjxTCQqgzbLpT4cgUTlYt2UjSgxZTxxKWyln74WIqezspxLVQ8egDb35MEJMK6PpX/WoCONzzaDNsqkn47lrDRH5szzsERB+bKJdyKrnyE9/8mgPfRoaDu+IRdkvzEIX9+9pbPNOXRjSb3ZH4OXUtDmF6ieTiouvi8ONSbHalwAyh/lD4Jht68tn11zx+8My7igAH251VEF+B2mpUGINy4lef7MMioppTv6kN3gCajIhcFD0d87VG8MnyXBbXGAQpkq6io2v/OTBw== 
   - secure: L20To/+xg6JAeUeyhS4iPXZj8yqciH08UEJbzuraAWUWgEAZ9Sd4sf9VBfzv3BB855NthIWXnAVJ2iPM355n4B5cbIwxPFLI9ajMkbq7MkuTIgJ9hRmT45unbRRja5jl2aF4e3qremUxeLT2uYqqrZQV00Fv+UJko3kCn6eDl5jWFynhUXnTef3IOqfmIChiJVTRuDj1PfxGsh7j4INzHkl3dEcbh5X5WLJkjiVBns+RdjQu13nMKGLZ4O5eAoczDVHyMkJ52274pqexbYYuOnSn7+zY7pSYq41w3GTJsPYVcGJ7UFx9tZQA0UGJDYI+5c6G/eyjPpm9Oka0kMxgzA== 
   - DOCKER_COMPOSE_VERSION="1.5.0rc3"
  
matrix:
  include:
    - jdk: openjdk7
      env: testproj=name
  exclude:
    - jdk: oraclejdk8
      env: DOCKER_COMPOSE_VERSION="1.5.0rc3"
  
before_script: echo $DOCKER_COMPOSE_VERSION and $final
      

#cache: true
